name: Setup Node.js
description: Setup Node.js and pnpm

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      with:
        version: 10.11.0

      # Cache node_modules
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: 20
        cache: 'pnpm'

    - run: pnpm install
      shell: bash
