import path from 'node:path';
import fs from 'node:fs';
import findPodfilePath from './findPodfilePath.js';
import findXcodeProject from './findXcodeProject.js';
import findAllPodfilePaths from './findAllPodfilePaths.js';
import { ApplePlatform, Params, ProjectConfig } from '../types/index.js';

export const getProjectConfig = (
  platformName: ApplePlatform,
  folder: string,
  userConfig: Params
): ProjectConfig | null => {
  const src = path.join(folder, userConfig.sourceDir ?? '');
  const podfile = findPodfilePath(src, platformName);

  /**
   * In certain repos, the Xcode project can be generated by a tool.
   * The only file that we can assume to exist on disk is `Podfile`.
   */
  if (!podfile) {
    return null;
  }

  const sourceDir = path.dirname(podfile);

  const xcodeProject = findXcodeProject(fs.readdirSync(sourceDir));

  return {
    sourceDir,
    xcodeProject,
  };
};

export const findPodfilePaths = findAllPodfilePaths;
